### ISSUE TITLE
[Q]: What's the ETA for this library ?

### ISSUE THREAD

**Issue by jakubczaplicki** [XeroAPI/xero-python#1]

**Comment by SidneyAllen** [comment]
@jakubczaplicki - we hope have our initial release in early May.

**Comment by jevonearth** [comment]
:hourglass_flowing_sand:   Looking forward to it :)

**Comment by SidneyAllen** [comment]
@jakubczaplicki and @jevonearth - xero-python is now publicly available.  Thanks for your patience.
