### ISSUE TITLE
Repeating Invoice doesn't return NextScheduledDate or EndDate

### ISSUE THREAD

**Issue by aidanlister** [XeroAPI/xero-python#102]
https://developer.xero.com/documentation/api/accounting/repeatinginvoices

https://github.com/XeroAPI/xero-python/blob/master/xero_python/accounting/models/repeating_invoice.py

**Comment by RettBehrens** [comment]
The [RepeatingInvoice](https://github.com/XeroAPI/xero-python/blob/master/xero_python/accounting/models/repeating_invoice.py) model includes the [Schedule](https://github.com/XeroAPI/xero-python/blob/master/xero_python/accounting/models/schedule.py) model which includes: 
- `NextScheduledDate` (calculated field)
- `EndDate` (optional field, only returned if the template has an end date set)
