### ISSUE TITLE
Need methods for creating and deleting repeating invoices

### ISSUE THREAD

**Issue by aracnid** [XeroAPI/xero-python#105]
The REST API was updated recently to allow for creating and deleting repeating invoices. (I would also like to see the update method, as well, but I can work with create and delete.)

Are the create and delete methods on the roadmap for xero-python? Are you looking for help?

**Comment by RettBehrens** [comment]
Hey @aracnid the methods you're looking for were released with [1.17.0](https://github.com/XeroAPI/xero-python/releases/tag/1.17.0)

**Comment by RettBehrens** [comment]
Please note - as with the REST API, it's a "soft delete" via a POST call updating the Status to DELETED.

**Comment by aracnid** [comment]
Oh, great! In that case then, I think only the documentation needs to be updated. I couldn't find them here: https://xeroapi.github.io/xero-python/v1/accounting/index.html
