### ISSUE TITLE
Dependency on python-dateutil is badly specified

### ISSUE THREAD

**Issue by cjsoftuk** [XeroAPI/xero-python#11]
I have identified in one of my projects that xero-python depends on python-dateutil with no minimum version when, in fact, a minimum required version exists.

Please could you consider specifying a minimum version of python-dateutil as 2.7 or higher (I believe there's a method introduced in python-dateutil 2.7 which this library depends on).

**Comment by SidneyAllen** [comment]
@cjsoftuk - thank you for the feedback.  Change made in version 1.0.6
