### ISSUE TITLE
Kitchen Sync App hyperlink

### ISSUE THREAD

**Issue by NateJones5150** [XeroAPI/xero-python#15]
Hi - Firstly, thanks so much for these examples, a really big help for us beginners.

I could be wrong, but the hyperlink under Kitchen Sync App header leads to the starter example (xero-python-oauth-starter) - I was expecting this to direct to another example walk through, similar to the start example.

Is this correct?

Thanks,
Nathan

**Comment by NateJones5150** [comment]
Actually I've just noticed I can simple go back one folder and get the app link from there - So all good :) Sorry to raise this before investigating further.

Cheers,
Nathan

**Comment by SidneyAllen** [comment]
Thanks for calling out the bad link ... fixed now.
