### ISSUE TITLE
XERO API Employee Classification is missing

### ISSUE THREAD

**Issue by briansuda** [XeroAPI/xero-python#22]
I am successfully getting the basic employee data back, but anything that seems sensitive is returning None even if I can see the information in the Web UI.

Specifically, I am trying to get the Employee's classification value.

[Screenshot of Web UI](https://i.stack.imgur.com/FzQty.png)

But the API seems to be removing any semi-sensitive/personal data:

{'employees': [{'bank_accounts': None,
                'classification': None,
                'date_of_birth': datetime.date(1984, 1, 26),
                'gender': 'M',
                ...
                'home_address': None,
                'start_date': datetime.date(2018, 8, 24),
                'status': <EmployeeStatus.ACTIVE: 'ACTIVE'>,
                'super_memberships': None,
                'tax_declaration': None,
                'termination_date': None,
                'title': None,
                'twitter_user_name': None,
                'updated_date_utc': datetime.datetime(2020, 9, 2, 8, 32, 26, tzinfo=tzutc()),
                'validation_errors': None}]}

I setup the scopes in OAuth to include payroll.employees payroll.timesheets payroll.settings

What I am missing to get the full data back via the API?

**Comment by SidneyAllen** [comment]
@briansuda - I'll try to find time to look at this one this week.

**Comment by SidneyAllen** [comment]
@briansuda - I've done a few tweak and released version 1.0.12.

I've tested your use case of an employee with a Classification (string) populated and I can see it returned and parsed successfully into the Employee object.  I've tested it using our companion app.

https://github.com/XeroAPI/xero-python-oauth2-app

The code is in on this line 
https://github.com/XeroAPI/xero-python-oauth2-app/blob/000fc8cf3e669d90ed54f01fe3f68cd07fb1d53c/app.py#L1427

**Comment by briansuda** [comment]
Hm... this is not working for me on the latest build xero-python==1.0.12 and the latest demo app.

It is still not returning the classification or other keys.

<img width="200" alt="Screen Shot 2020-10-12 at 09 42 28" src="https://user-images.githubusercontent.com/173116/95731849-88259680-0c6f-11eb-949c-3c75385a228d.png">

with some debugging, the json returned before serialize_model() has the keys, but they are set to None.

'classification': None,
'job_title': None,
'title': None,

Is there a setting somewhere in the xero.com config to allow this to be sent or restricted to the api?

Is there away to open a specific support ticket and we can review the actual user account?

**Comment by SidneyAllen** [comment]
@briansuda - there aren't any configuration to restrict what is returned via the API.

To clarify, you are working with AU Payroll and you are doing a GET on a single Employee correct?  Not a GET on all employees?

In the API documentation a GET all employees returns less detail, than a GET on an employee with a specific employee_id.

https://developer.xero.com/documentation/payroll-api/employees#GET
