### ISSUE TITLE
Endpoint for Employee Rates?

### ISSUE THREAD

**Issue by enod** [XeroAPI/xero-python#3]
Hi there,

It seems like there is no endpoint for employee rates. What is the best way to pull that information from xero automatically?

Thanks,

**Comment by SidneyAllen** [comment]
@enod - which API endpoints are you looking for?  I assume payroll, is that AU, UK, NZ?

**Comment by enod** [comment]
Billable rate. AU.
Thanks!

**Comment by SidneyAllen** [comment]
@enod - to clarify are you making an API feature request? Maybe you could share a link to the AU payroll endpoint you're referring to in our docs?
https://developer.xero.com/documentation/payroll-api/overview

**Comment by SidneyAllen** [comment]
@enod - we've added support for AU Payroll in version 0.5.1 of the xero-python sdk
