### ISSUE TITLE
No refresh_token without "offline_access" scope

### ISSUE THREAD

**Issue by ryanking1809** [XeroAPI/xero-python#46]
The `ApiClient` appears to expect a `refresh_token` which is not provided if the `offline_access` scope is not requested.
As a workaround, I'm adding `response['refresh_token'] = None` to the `authorized_response()`. It does the trick, but I don't believe it should be necessary.

```python
def verify():
        try:
            response = xero.authorized_response()
        except Exception as e:
            print(e)
            raise
        # todo validate state value
        if response is None or response.get("access_token") is None:
            return "Access denied: response=%s" % response
        response['refresh_token'] = None
        store_token(response)
```

**Comment by RettBehrens** [comment]
Hey @ryanking1809 apologies for the long delay on this one. Discovered this myself when working to implement client credentials grant flow. The api client was indeed coded such that any app not receiving a refresh token would have encountered an error. This was corrected with the latest [release](https://github.com/XeroAPI/xero-python/releases/tag/1.8.0).

It wasn't the `authorized_response()` method from flask-oauthlib that was causing the error but rather the `api_client token_saver` decorator associated with the sample app's `store_token` method that also stores the token in the session. When the `api_client token_saver` decorator is called it's also calling `update_token`, which until recently the refresh token was not an optional param. This has been [fixed](https://github.com/XeroAPI/xero-python/blob/c15519022503339df6a0218b181ae90239972e74/xero_python/api_client/oauth2.py#L277).
