### ISSUE TITLE
No documentation on how to upload a File

### ISSUE THREAD

**Issue by micheledicosmo** [XeroAPI/xero-python#47]
A bit of information on how to upload files using the Files API would be useful to get started using it.

I tried uploading bytes, an instance of BytesIO, and MIME formatted content, all of which results in the error `ValueError: Can't serialize value type 'type'`.

What is the expected format of the content of the file?

**Comment by SidneyAllen** [comment]
Hey 👋  @micheledicosmo - thanks for the feedback.

We are working SDK with runnable code snippets and fleshing out or companion app.

Here is the code we use in our companion app for uploading a file.

    name = "helo-heros"
    filename= "helo-heros.jpg"
    mime_type = "image/jpg"
    with open('helo-heros.jpg', 'rb') as f:
        body = f.read()

    try:
        file_object = files_api.upload_file(
            xero_tenant_id, 
            name = name, 
            filename= filename, 
            mime_type = mime_type,
            body=body
        )
    except AccountingBadRequestException as exception:
        json = jsonify(exception.error_data)
    else:
        json = serialize_model(file_object)

**Comment by micheledicosmo** [comment]
Thank you!
