### ISSUE TITLE
Scope checking is too strict and causes error when the number of scopes requested is reduced

### ISSUE THREAD

**Issue by wobinb** [XeroAPI/xero-python#48]
Scopes in Xero's OAuth 2.0 implementation are additive.

If the first time a connection is authorised scopes A, B and C are requested, they will always be included.

On a second authorisation for the same user, if only scopes A and B are requested, C will also be returned.

The SDK appears to then do a validation check to verify the scopes returned match the ones requested, and the process fails.

To recreate:

1. Set the scopes to include _payroll.employees_ and complete the authorisation process for one user.
2. Remove the _payroll.employees_ and repeat the authorisation process for the same user.
3. Observe the process fails with a _Scope has changed from..._ error

**Comment by RettBehrens** [comment]
Per the [docs](https://developer.xero.com/documentation/oauth2/scopes) around scope:

"It's not possible to remove scopes from an existing access token. The only way to reduce consented scopes is to revoke the token and start again."

As part of the described steps to replicate above, does the user disconnect from Xero via the connected apps dashboard or does Xero consider the app already authenticated (option is grey and continue with 1 org text present) during the second auth flow?

**Comment by weyersma** [comment]
I have the same issue. When the user signs up, I grant all the access. On subsecuent sign ins I only ask for a limited scope but then I get an exception because I am asking a lighter scope.

Am I implementing the difference in scope for Sign In and Sign Up Incorrectly?

**Comment by wobinb** [comment]
@RettBehrens in the replication steps above the app remains connected, so it would essentially be a re-authentication

Seems to still be an issue, see: https://github.com/XeroAPI/xero-python/issues/73

**Comment by RettBehrens** [comment]
The following solution has been identified https://github.com/XeroAPI/xero-python-oauth2-app/pull/47
