### ISSUE TITLE
How to (Manual/documentation)

### ISSUE THREAD

**Issue by mykolavasylchenko** [XeroAPI/xero-python#7]
Hello! I have Client id, Client secret credentials. I want to generate an invoice for each user. Could you please lead me on how can I do that?
http://i.imgur.com/viSyeW7.png
That's what I've tried - no success.
Please help/provide any useful manual/documentation for SDK.

**Comment by SidneyAllen** [comment]
Hi @mykolavasylchenko 

Documentation specific to this SDK is still to be developed.  In the meantime, I suggest looking at our API reference docs.
https://developer.xero.com/documentation/api/api-overview

We have created a starter project that shows how to authenticate and make your first API call.
https://github.com/XeroAPI/xero-python-oauth2-starter

Here is an example of creating an invoice once you have your access token and xero tenant id

`xero_tenant_id = get_xero_tenant_id()
    accounting_api = AccountingApi(api_client)    

    contact = Contact(
        contact_id=contact_id
    )
    
    line_item = LineItem(
        account_code=account_id,
        description= "Consulting",
        quantity=1.0,
        unit_amount=10.0,
    )
    
    invoice = Invoice(
        line_items=[line_item],
        contact=contact,
        due_date= dateutil.parser.parse("2020-09-03T00:00:00Z"),
        date= dateutil.parser.parse("2020-07-03T00:00:00Z"),
        type="ACCREC"
    )
    
    invoices = Invoices(invoices=[invoice])
    
    try:
        created_invoices = accounting_api.create_invoices(
            xero_tenant_id, invoices=invoices
        ) 
    except AccountingBadRequestException as exception:
        output = "Error: " + exception.reason
        json = jsonify(exception.error_data)
    else:  
        output = "New invoices status is '{}'.".format(
            getvalue(created_invoices, "invoices.0.status", "")
        )
        json = serialize_model(created_invoices)`

**Comment by mykolavasylchenko** [comment]
Thanks! Do you have the same starter project but for Django as well?
https://github.com/XeroAPI/xero-python-oauth2-starter

**Comment by SidneyAllen** [comment]
Hey @mykolavasylchenko - not a bad suggestions, but we've got limited resources.  We'd love to see someone from the python community create a Django starter project and let us know about so we could link to it from this repo. :-)
