### ISSUE TITLE
Filter Trial Balance Reports by Tracking Categories

### ISSUE THREAD

**Issue by benjimeltzer** [XeroAPI/xero-python#9]
Is it possible to filter our Trial Balance Reports in the `get_report_trial_balance` method by Tracking Categories - as in the front-end (see screenshot below)?
![image](https://user-images.githubusercontent.com/11029893/89035382-1cec4980-d33b-11ea-97bc-f6bb90e396ad.png)

**Comment by SidneyAllen** [comment]
@benjimeltzer - I'm sorry but this version of the trial balance report is not exposed via Xero's APIs.

We have our original v1 reports which are more static and available via the reports endpoint. Xero released v2 reports which are not exposed via our APIs.  These reports are not on our public roadmap https://trello.com/c/vONmjBSm/1-welcome-to-the-xero-developer-roadmap

But you can voice your interest here in enhancing the API here https://xero.uservoice.com/forums/5528-xero-accounting-api?query=trial

In the Reports menu, you'll see a "new" tag next to the v2 reports which are not available as well as the v1 reports.

![Screen Shot 2020-07-31 at 11 17 09 AM](https://user-images.githubusercontent.com/595967/89064890-a4c45a80-d31f-11ea-8339-f1ea32b529bd.png)
